apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pure-transformer-data
  namespace: ucsdfutures
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: rook-cephfs
